### ISSUE TITLE
License

### ISSUE THREAD

**Issue by jachym** [Melown/open-source-process#1]
Project has a LICENSE file with an open source license

- [x] vts-browser-js

**Comment by ondra-prochazka** [comment]
I have added the BSD 3-clause license to melown-js repository. Please allow another 24 hours before taking the license choice as official.

We shall use the license as follows:

 * every repository shall include the LICENSE file
 * JS libraries need not include the license in every source code file but the license shall be present at the top of every library build
 * C++ based projects will include the license at the top of every source code file

The latter two points are open for discussion.

**Comment by ondra-prochazka** [comment]
* Final license choice: BSD-2 clause.

Closing.

**Comment by jachym** [comment]
solved in https://github.com/Melown/melown-js/issues/8 for javascript part `vts-browser-js`

**Comment by ondra-prochazka** [comment]
Top of js builds, example:

```
/**
 * Copyright (c) 2017 Melown Technologies SE
 * For terms of use, see accompanying LICENSE file.
 */
```

**Comment by jachym** [comment]
Done in https://github.com/Melown/vts-browser-js/pull/23
