### ISSUE TITLE
Basic Documentation

### ISSUE THREAD

**Issue by jachym** [Melown/open-source-process#2]
Project has basic documentation 

- [x] README
- [x] CONTRIBUTING
- [x] CODE_OF_CONDUCT

**Comment by jachym** [comment]
* Code of conduct Draft: https://github.com/Melown/open-source-process/wiki/Code-of-conduct-(Draft)
* Contributing: https://github.com/Melown/open-source-process/wiki/Contributing-(DRAFT)

**Comment by jachym** [comment]
@ondra-prochazka  please review CoC

**Comment by ondra-prochazka** [comment]
@jachym CoC seems fine in principle, copyedited.

community@melown.org now points to @jachym 

An alternative for discussion: http://contributor-covenant.org/version/1/4/

**Comment by ondra-prochazka** [comment]
@jachym CoC 
```
Code of conduct

Everyone is invited to participate in Melown Techonlogies SE’s open source projects and public discussions: we want to create a welcoming and friendly environment. Harassment of participants or other unethical and unprofessional behavior will not be tolerated in our spaces. The Contributor Covenant applies to all projects under the Melown Technologies SE organization and we ask that you please read the full text.
```

contributor covenant link: http://contributor-covenant.org/version/1/4/

**Comment by ondra-prochazka** [comment]
On second thought, I think it is a better idea to include the text of contributor covenant verbatim into CODE_OF_CONDUCT.md for each project. The email address in "enforcement" section should be community@melown.com - currently goes to @jachym .

**Comment by jachym** [comment]
solved in  https://github.com/Melown/vts-browser-js/pull/26
